# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту artress@ngs.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - artress@ngs.ru
    on_success: never # default: change
    on_failure: always # default: always

# Start PostgreSQL
services:
- postgresql
before_script:
- psql -c "CREATE DATABASE tracker;" -U postgres
- psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres