# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk:
  - openjdk11

cache:
  directories:
  - $HOME/.m2

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту artress@ngs.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - artress@ngs.ru
    on_success: never # default: change
    on_failure: always # default: always

# Start PostgreSQL
services:
- postgresql
before_install:
- psql -c "CREATE DATABASE tracker;" -U postgres
- psql -c "CREATE DATABASE sqlru;" -U postgres
- psql -c "CREATE DATABASE sqlrutest;" -U postgres
- psql -c "CREATE DATABASE users;" -U postgres
- psql -c "CREATE DATABASE users_test;" -U postgres